quarkus:
  http:
    cors:
      # Abilita il supporto CORS
      enabled: true
      # Specifica le origini Vue/Vite (localhost:5173)
      origins:
        - "http://localhost:5173"
        - "http://127.0.0.1:5173"
  log:
    level: DEBUG 
  mongodb:
    connection-string: mongodb+srv://adrianaridolfi91_db_user:Sk7pqSWAGz4J5wBg@bibliomap.vhw9x8v.mongodb.net/
    database: bibliomap
  
  # CONFIGURAZIONE SERVIZI DI AUTENTICAZIONE
  auth:
    otp:
      mock-enabled: true # Imposta a 'false' per inviare email reali
      from: "bibliomap@noreply.it"

  # CONFIGURAZIONE QUARKUS MAILER (SMTP)
  mailer:
    host: smtp.gmail.com 
    port: 587 
    ssl: true
    username: adriana.ridolfi@studenti.unipegaso.it 
    password: cevn vrbe vvgs jvte  
    start-tls: required 
